### ISSUE TITLE
Submit to maven central?

### ISSUE THREAD

**Issue by travisdowns** [jasonwjones/Jolo#1]
Not sure if this project is still being actively developed, but it would be nice if this could be pushed to Maven central...

**Comment by jasonwjones** [comment]
It's used a lot internally still. I'll clean it up and get it in Central, thanks for the idea!

**Comment by jasonwjones** [comment]
I just cleaned it up a bit and pushed it out to Maven Central -- should be available in a day or two I think. It's been awhile so hopefully I didn't goof anything up... I had some issues with my GPG key but I think I got it sorted out. Thanks for suggesting to send it up to Central.

**Comment by travisdowns** [comment]
Thanks on the awesome quick response!

**Comment by jasonwjones** [comment]
No problem -- looks like it made it in to Central already.
